<a href="https://colab.research.google.com/github/Gnome101/MAT_422/blob/main/Module_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1.2 Linear Algebra

## 1.2.1 Linear Spaces


Linear Combination: A new vector made from a subset by multipling vectors together with a constant(or a scalar) and then adding the results

Span: The span of a list or set of vectors is the set of all linear combinations of those vectors

Linear Subspace: A subset of a vector space that includes the zero vector and is closed under vector addition and scalar multipication.

Linear Independence: A list of vectors is linearly indepdenent if none of them can be written as a linear combination of others.

Linear Dependence: A list of vectors are linearly depdendent if they are not linearly independent.

Basis:  A set of vectors that makes all of the elements of a vector space, and these vectors are linearly independent.

Dimension: The number of rows x columns of a matrix.

Rank: The dimension of a column space of A

For a $m$ $x$ $n$  matrix $A$, the rank is the largest number of linearly independent row vectors. If the rank is m, then the vectors are linearly independent, if the rank is less than m then they are dependent.

Dimension Theorem: If $U$ is a subspace of $V$ then the number of vectors in a basis of $U$ will be less than or equal to dim($V$).






In [ ]:
import numpy as np
#We will make vectors x and y in numpy
x = np.array([1, 2, 3])
y = np.array([3, 1, 4])

#a is a linear combination of x and y
a = x + y * 2
print("Linear Combination of vector x & y:",a)


Linear Combination of vector x & y: [ 7  4 11]


In [ ]:
def isLinearIndependent(A):
  colunm_count = A.shape[1]
  if(np.linalg.matrix_rank(A) == colunm_count): print("This array is linearly independent ")
  else: print("This array is linearly dependent")

In [122]:
#matrix_rank gives the rank of a matrix
#The number of columns of the matrix below is 3
# 1 2
# 2 4
# 3 6

A = np.array([[1, 2, 3], [2, 4, 6], ])
isLinearIndependent(A)
#This makes sense because for example we can form a linear combination equal to the second column
t = np.array_equal((A[0] * 2 + A[1] * 0 ) , A[1])
print(t)

This array is linearly dependent
True


In [123]:
I = np.identity(3)
# 1 0 0
# 0 1 0
# 0 0 1
#The identiy matrix is linearly independent because the columns cannot equal each other
isLinearIndependent(I)

This array is linearly independent 


## 1.2.2 Orthogonalitiy


Orthonormal bases can simplify mathematical representations.

A list of vectors $\{ u_1, ..., u_i\}$ is orthonormal if the $u_i$ are pairwise orthonormal. Essentially each $u_i$ must have a dot product of 0.

A dot product is shown by ⟨x,y⟩

Best Approximation Theorem: If $W$ is a subspace of a vector space $V$, and if $v$ is any vector in $V$ then the orthogonal projection of $v$ onto $W$ is the closest vector in $W$ to $v$.

Orthogonal Projection:
The orthogonal projection of a vector onto a subspace is the closest point in the subspace to the vector. The vector and its difference is orthogonal to the subspace.

In [ ]:
def isOrthogonal(v1,v2):
    # Have to use the isClose because of python rounding erros :(
    x = np.isclose(np.dot(v1, v2), 0, atol=1e-8)
    if(x): print("These are orthogonal")
    if(not x): print("These are not orthogonal")


In [ ]:
# The dot product of x and y will be shown below
b = np.dot(x,y)
print(b)

isOrthogonal(x,y)
#Since the dot product is not 0, they are not orthogonal
o1 = np.array([-1, 2, 0])
o2 = np.array([4, 2, 0])

isOrthogonal(o1,o2)
#Since the dot prodcut of o1 and o2 is -1 * -4 + 2 * 2 + 0 * 0 = 0 then they are orthogornal



17
These are not orthogonal
These are orthogonal


In [ ]:
v = np.array([3, 4])
w = np.array([1, 2])



## 1.2.3 Gram-Schmidt Process


The Gram-Schmidt algorithm is used to obtain an orthonormal basis.

Let $a_1,...,a_m$ in $R^n$ be linearly independent.
Then there exists an orthonormal basis $q_1,...,q_m$ of a span

Start with a set of linearly independent vectors

Then set the first vector as the first orthogonal vector.

Then project each subsequent vector onto the subspace spanned by the previous orthogonal vector.



In [121]:
#
v = np.array([3, 4])
w = np.array([1, 2])

u1 = v

u1_norm = np.dot(u1, u1)

proj_w_u1 = (np.dot(w, u1) / u1_norm) * u1
u2 = w - proj_w_u1

isOrthogonal(u1,u2)



These are orthogonal


## 1.2.4 Eigenvalues and Eigen Vectors

Eigenvalue is a constant such that if $A \in R^{dxd}$ where A is a square matrix.

Then $\lambda \in R$ is an eigenvalue of A if there exists a nonzero vector such that $Ax = \lambda x $

The number of eigenvalues for $A$ is at most d.

The vector x is referred to as the eigen vector.
An eigenvector is a vector where its direction does not change after a linear transformation.

If a matrix is symmetric, then any of its two eigenvectros are orthogonal.

### Spectral Theorem for Symmetric Matrices
An $n$ x $n$ symmetric matrix is called A then it has these properties:

*   $A$ has $n$ real eigenvalues
*   If \lambda is an eigenvalue of A with a multiplicity k, then the eigenspace of \lambda is k-dimensional
*   The eigenspaces are mutually orthogonal, essentially each distinct eigenvector is orthogonal
*  A is orthogonally diagonalizable


For $Ax = \lambda x$, the eigenspace $E_\lambda$ is defined as

$E_\lambda$ = $\{x \in \mathbb{R}^n  | Ax = \lambda x\}$

So its the set of all vectors $x$ that are mapped to a scalar mutiple of themselves.


### Constrained Optimization
This is useful for optimization problems.

Let $A$ be a $n$ $x$ $n$ matrix with an orthogonal diagonilzation of $P$$DP^{-1}$
The columns of P are orthonromal eigenvectors. The diagonal of $D$ are arranged so that $\lambda_1 \le \lambda_2 \le ... \lambda_n$

$min_{x \neq 0} \frac{x^TAx}{x^Tx} = \lambda_1$

$max_{x \neq 0} \frac{x^TAx}{x^Tx} = \lambda_n$

In [ ]:
#Make a matrix of random numbers:
A = np.random.randint(0,10,(3,3))
print(A)
eig_value,eig_vect = np.linalg.eig(A)

print("eigenvalues: ", eig_value)
print("eigenvectors: ", eig_vect)





[[5 3 8]
 [2 8 7]
 [4 9 9]]
eigenvalues:  [18.94018144  3.60214025 -0.54232169]
eigenvectors:  [[-0.5052034  -0.91587908 -0.70804903]
 [-0.52875854  0.40134109 -0.34096642]
 [-0.68204394  0.0095309   0.61839184]]
